apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  DB_USERNAME: myuser
  DB_NAME: mydatabase
  DB_HOST: "10.100.50.198"
  DB_PORT: "5432"
---  
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==
